-- Driver onboarding lookup catalogs.
-- These are deliberately separate from profiles so onboarding can offer
-- searchable, consistent values without allowing drivers to edit the catalog.

CREATE TABLE IF NOT EXISTS public.driver_vehicle_makes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.driver_vehicle_colors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.driver_operating_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  locality_type TEXT NOT NULL DEFAULT 'village'
    CHECK (locality_type IN ('city', 'town', 'township', 'village', 'area')),
  route_group TEXT NOT NULL DEFAULT 'Tzaneen–The Oaks R36 corridor',
  route_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.driver_operating_areas
  ADD COLUMN IF NOT EXISTS route_order INTEGER NOT NULL DEFAULT 0;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_driver_vehicle_makes_name
  ON public.driver_vehicle_makes (lower(name));
CREATE INDEX IF NOT EXISTS idx_driver_vehicle_makes_trgm
  ON public.driver_vehicle_makes USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_driver_vehicle_colors_name
  ON public.driver_vehicle_colors (lower(name));
CREATE INDEX IF NOT EXISTS idx_driver_vehicle_colors_trgm
  ON public.driver_vehicle_colors USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_driver_operating_areas_name
  ON public.driver_operating_areas (lower(name));
CREATE INDEX IF NOT EXISTS idx_driver_operating_areas_trgm
  ON public.driver_operating_areas USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_driver_operating_areas_route_order
  ON public.driver_operating_areas (route_group, route_order, lower(name));

ALTER TABLE public.driver_vehicle_makes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_vehicle_colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_operating_areas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_can_read_driver_vehicle_makes"
  ON public.driver_vehicle_makes;
CREATE POLICY "authenticated_can_read_driver_vehicle_makes"
  ON public.driver_vehicle_makes FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated_can_read_driver_vehicle_colors"
  ON public.driver_vehicle_colors;
CREATE POLICY "authenticated_can_read_driver_vehicle_colors"
  ON public.driver_vehicle_colors FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "authenticated_can_read_driver_operating_areas"
  ON public.driver_operating_areas;
CREATE POLICY "authenticated_can_read_driver_operating_areas"
  ON public.driver_operating_areas FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.driver_vehicle_makes TO authenticated;
GRANT SELECT ON public.driver_vehicle_colors TO authenticated;
GRANT SELECT ON public.driver_operating_areas TO authenticated;

-- Broad canonical passenger-vehicle make seed. This intentionally includes
-- major current and historical marques from Africa, the Americas, Europe,
-- Asia, and Oceania; the catalog remains extensible by an admin migration.
INSERT INTO public.driver_vehicle_makes (name)
SELECT make FROM unnest(ARRAY[
  'Abarth','AC Cars','Acura','Aixam','Alfa Romeo','Alpina','Alpine','AMC',
  'Aston Martin','Audi','Austin','BAIC','Baojun','Bentley','BMW','Borgward',
  'Brilliance','Bugatti','Buick','BYD','Cadillac','Caterham','Changan',
  'Chery','Chevrolet','Chrysler','Citroen','Cupra','Dacia','Daewoo','Daihatsu',
  'Datsun','DeLorean','Dodge','Dongfeng','DS Automobiles','Eagle','FAW',
  'Ferrari','Fiat','Fisker','Ford','Foton','GAC','Geely','Genesis','GMC',
  'GWM','Hafei','Haima','Haval','Holden','Honda','Hongqi','Hummer','Hyundai',
  'Infiniti','Isuzu','Iveco','JAC','Jaguar','Jeep','Jetta','Kia','Koenigsegg',
  'Lada','Lamborghini','Lancia','Land Rover','Lexus','Lincoln','Lotus','Lucid',
  'Mahindra','Marcos','Maserati','Maybach','Mazda','McLaren','Mercedes-Benz',
  'Mercury','MG','Mini','Mitsubishi','Mitsuoka','Morgan','Morris','Moskvich',
  'NIO','Nissan','Oldsmobile','Opel','Pagani','Peugeot','Plymouth','Polestar',
  'Pontiac','Porsche','Proton','RAM','Renault','Rimac','Rivian','Rolls-Royce',
  'Rover','SAAB','Samsung Motors','Saturn','Scion','Scorpio','Seat','Seres',
  'Shelby','Shacman','Skoda','Smart','Soueast','SsangYong','Steyr','Studebaker',
  'Subaru','Suzuki','Tata','Tesla','Toyota','Trabant','Triumph','TVR','UAZ',
  'Vauxhall','Vector','VinFast','Volkswagen','Volvo','Wartburg','Wiesmann',
  'Wuling','XPeng','Yugo','ZAZ','Zenvo',
  'Alfa Romeo South Africa','Austin Rover','BMC','Birkin','Cobra','Conquest',
  'Fiat South Africa','Gonow','Jurgens','Mureza','Perana','Samil','Uri',
  'Volkswagen South Africa','Zeda',
  'Acadian','Allard','American Motors','Autocar','Autobianchi','Bajaj','Brammo',
  'Checker','Cisitalia','Cord','Crosley','Duesenberg','Edsel','Facel Vega',
  'Geo','Goggomobil','Goliath','Gordon-Keeble','Graham','Hudson','Hupmobile',
  'Imperial','Jensen','Kaiser','LaSalle','Mercury','Nash','Packard','Panoz',
  'Pierce-Arrow','Rambler','Reliant','Riley','Singer','Sunbeam','Talbot','Willys',
  'Zastava','AITO','Arcfox','Aurus','Baojun','Bestune','Chery Exeed','Denza',
  'Forthing','GAC Aion','Great Wall','HiPhi','Hongqi','Jetour','Karma','Leapmotor',
  'Li Auto','Lynk & Co','Maxus','Skywell','Smart','Tank','Voyah','Weltmeister',
  'ZEEKR','Hino','Mack','MAN','Scania','UD Trucks','Isuzu Trucks','Mitsubishi Fuso',
  'Mercedes-Benz Trucks','Volvo Trucks','DAF','Iveco Trucks','Kamaz','Sinotruk'
]::TEXT[]) AS make
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.driver_vehicle_colors (name)
SELECT color FROM unnest(ARRAY[
  'Black','White','Pearl White','Ivory','Cream','Silver','Platinum','Grey','Charcoal',
  'Gunmetal','Blue','Navy Blue','Light Blue','Sky Blue','Red','Maroon','Burgundy',
  'Orange','Copper','Yellow','Gold','Green','Dark Green','Lime','Teal','Turquoise',
  'Brown','Beige','Tan','Bronze','Purple','Violet','Pink','Magenta','Multi-colour',
  'Two-tone','Other'
]::TEXT[]) AS color
ON CONFLICT (name) DO NOTHING;

-- Settlements and named localities used when operating between Tzaneen and
-- The Oaks. This is a practical R36 corridor catalog, not a claim that every
-- informal settlement or farm name in the wider Mopani district is included.
INSERT INTO public.driver_operating_areas (name, locality_type, route_order)
VALUES
  ('Tzaneen', 'town', 10),
  ('Dan Village', 'village', 20),
  ('Nkowankowa', 'township', 30),
  ('Mokgoloboto', 'village', 40),
  ('Matafuleni', 'village', 50),
  ('Maake', 'village', 60),
  ('Ha-Maake', 'village', 70),
  ('Maake Plaza', 'area', 75),
  ('Khopo', 'village', 80),
  ('Morokolotsi', 'village', 90),
  ('Letsitele', 'town', 100),
  ('Lenyenye', 'village', 110),
  ('Gravelotte', 'town', 120),
  ('Ofcolaco', 'village', 130),
  ('The Oaks', 'village', 140),
  ('Trichardtsdal', 'village', 150),
  ('Calais', 'village', 160),
  ('Hoedspruit', 'town', 170),
  ('Maruleng', 'area', 180)
ON CONFLICT (name) DO NOTHING;

-- Native Flutter onboarding preloads these small catalogs, while these RPCs
-- remain available for server-side typeahead and future admin tooling.
CREATE OR REPLACE FUNCTION public.search_driver_vehicle_makes(
  p_query TEXT DEFAULT '',
  p_limit INTEGER DEFAULT 25
)
RETURNS TABLE (name TEXT)
LANGUAGE SQL STABLE SECURITY INVOKER SET search_path = public
AS $$
  SELECT m.name
  FROM public.driver_vehicle_makes m
  WHERE NULLIF(trim(p_query), '') IS NULL
     OR m.name ILIKE '%' || trim(p_query) || '%'
  ORDER BY CASE WHEN m.name ILIKE trim(p_query) || '%' THEN 0 ELSE 1 END, m.name
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 25), 1), 1000);
$$;

CREATE OR REPLACE FUNCTION public.search_driver_vehicle_colors(
  p_query TEXT DEFAULT '',
  p_limit INTEGER DEFAULT 25
)
RETURNS TABLE (name TEXT)
LANGUAGE SQL STABLE SECURITY INVOKER SET search_path = public
AS $$
  SELECT c.name
  FROM public.driver_vehicle_colors c
  WHERE NULLIF(trim(p_query), '') IS NULL
     OR c.name ILIKE '%' || trim(p_query) || '%'
  ORDER BY CASE WHEN c.name ILIKE trim(p_query) || '%' THEN 0 ELSE 1 END, c.name
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 25), 1), 1000);
$$;

CREATE OR REPLACE FUNCTION public.search_driver_operating_areas(
  p_query TEXT DEFAULT '',
  p_limit INTEGER DEFAULT 25
)
RETURNS TABLE (name TEXT, locality_type TEXT)
LANGUAGE SQL STABLE SECURITY INVOKER SET search_path = public
AS $$
  SELECT a.name, a.locality_type
  FROM public.driver_operating_areas a
  WHERE NULLIF(trim(p_query), '') IS NULL
     OR a.name ILIKE '%' || trim(p_query) || '%'
  ORDER BY CASE WHEN a.name ILIKE trim(p_query) || '%' THEN 0 ELSE 1 END,
           CASE WHEN a.route_group = 'Tzaneen–The Oaks R36 corridor' THEN 0 ELSE 1 END,
           a.route_order,
           a.name
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 25), 1), 1000);
$$;

GRANT EXECUTE ON FUNCTION public.search_driver_vehicle_makes(TEXT, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_driver_vehicle_colors(TEXT, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_driver_operating_areas(TEXT, INTEGER) TO authenticated;
